import "./globals.css";
import {Poppins, Oxanium} from "next/font/google";
import {Header} from "@/components/Header";
import {Footer} from "@/components/Footer";
//Suisse Int'l
const oxanium = Oxanium({
    subsets: ["latin"],
    weight: ['300','400','500', '600', '700'],
    variable: '--font-Oxanium'
});
const poppins = Poppins({
    subsets: ["latin"],
    weight: ['300','400','500', '600', '700', '800'],
    variable: '--font-Poppins'
})
export const metadata = {
    title: 'ByteexTestLand',
    description: 'Generated by create next app',
    icon: '/favicon.ico'
};

export default function RootLayout({ children }) {
    return (
        <html lang= 'en'>
        <body className = {`${oxanium.variable} ${poppins.variable} antialiased`}>
        <Header/>
        {children}
        <Footer/>
        </body>
        </html>
    );
}
